#### Overfitting

usage of too many features while training your data.. The task you have in hand is to classify ball.

    -    Shape - Round
    -    Weight - 125 gm to 250 gm
    -    Radius - 5.6 cm
    -    Usage - Play

200 data points based on the above data is being trained. So my model knows -

    -   A ball has to be round
    -   A ball must weigh between 125 gm to 250 gm
    -   The use of a ball is to play
    -   The ball must be of 5.6 cm radius

A new data comes in with below fetures -

    -    Shape - Round
    -    Weight - 185 gm
    -    Radius - 8.6 cm
    -    Usage - Play



You Are doing a sitcom classification system -

    -   Length 20 to 30 minutes episode
    -   background Laughing track
    -   Cast includes mathew perry , david schwimer 

Movie classification -

-   Thriller
    -   Action should be there
    -   Suspense should be there
    -   A strong villain presence is required
    -   Must include ajay devgan

In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [39]:
df = pd.DataFrame(data = [['round',5.6,185,'play','ball'],
                          ['round',5.6,165,'play','ball'],
                          ['round',5.6,155,'play','ball'],
                          ['triangle',8.6,275,'play','Boomerang'],
                          ['round',5.6,210,'play','ball'],
                          ['round',5.6,225,'play','ball'],
                          ['round',5.6,245,'play','ball'],
                          ['triangle',6.6,285,'play','Boomerang'],
                          ['triangle',9.6,235,'play','Boomerang'],
                          ['round',5.6,201,'play','ball'],
                          ['round',5.6,195,'play','ball'],
                          ['round',5.6,186,'play','ball'],
                          ['round',5.6,178,'play','ball'],
                          ['round',5.6,174,'play','ball'],
                          ['round',5.6,170,'play','ball'],
                          ['round',5.6,172,'play','ball'],], columns = ['shape','radius','weight','usage','label'])

In [40]:
df.head()

shape  radius  weight usage      label
0     round     5.6     185  play       ball
1     round     5.6     165  play       ball
2     round     5.6     155  play       ball
3  triangle     8.6     275  play  Boomerang
4     round     5.6     210  play       ball

In [41]:
le = LabelEncoder()

In [42]:
objlst = df.select_dtypes(include = 'object').columns

In [43]:
objlst

Index(['shape', 'usage', 'label'], dtype='object')

In [44]:
for i in objlst:
    df[i] = le.fit_transform(df[i])

In [45]:
df.head()

shape  radius  weight  usage  label
0      0     5.6     185      0      1
1      0     5.6     165      0      1
2      0     5.6     155      0      1
3      1     8.6     275      0      0
4      0     5.6     210      0      1

In [46]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [47]:
x

shape  radius  weight  usage
0       0     5.6     185      0
1       0     5.6     165      0
2       0     5.6     155      0
3       1     8.6     275      0
4       0     5.6     210      0
5       0     5.6     225      0
6       0     5.6     245      0
7       1     6.6     285      0
8       1     9.6     235      0
9       0     5.6     201      0
10      0     5.6     195      0
11      0     5.6     186      0
12      0     5.6     178      0
13      0     5.6     174      0
14      0     5.6     170      0
15      0     5.6     172      0

In [48]:
y

0     1
1     1
2     1
3     0
4     1
5     1
6     1
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: label, dtype: int32

In [49]:
scaler = StandardScaler()

In [50]:
scaler.fit_transform(x)

array([[-0.48038446, -0.42640143, -0.48614822,  0.        ],
       [-0.48038446, -0.42640143, -1.01171387,  0.        ],
       [-0.48038446, -0.42640143, -1.27449669,  0.        ],
       [ 2.081666  ,  2.13200716,  1.87889719,  0.        ],
       [-0.48038446, -0.42640143,  0.17080884,  0.        ],
       [-0.48038446, -0.42640143,  0.56498307,  0.        ],
       [-0.48038446, -0.42640143,  1.09054872,  0.        ],
       [ 2.081666  ,  0.42640143,  2.14168001,  0.        ],
       [ 2.081666  ,  2.98481003,  0.82776589,  0.        ],
       [-0.48038446, -0.42640143, -0.06569571,  0.        ],
       [-0.48038446, -0.42640143, -0.2233654 ,  0.        ],
       [-0.48038446, -0.42640143, -0.45986994,  0.        ],
       [-0.48038446, -0.42640143, -0.6700962 ,  0.        ],
       [-0.48038446, -0.42640143, -0.77520933,  0.        ],
       [-0.48038446, -0.42640143, -0.88032246,  0.        ],
       [-0.48038446, -0.42640143, -0.82776589,  0.        ]])

In [51]:
xtrain , xtest , ytrain , ytest = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [52]:
xtest.shape

(4, 4)

In [53]:
lr = LogisticRegression()

In [54]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [55]:
lr.score(xtest,ytest)

1.0

In [56]:
xtest

shape  radius  weight  usage
0       0     5.6     185      0
1       0     5.6     165      0
5       0     5.6     225      0
14      0     5.6     170      0

In [57]:
ytest

0     1
1     1
5     1
14    1
Name: label, dtype: int32

In [58]:
ypred = lr.predict(xtest)

In [59]:
ypred

array([1, 1, 1, 1])

In [60]:
nd = pd.DataFrame(data = [[0,7.6,154,0],
[0,8.6,195,0],[0,9.6,144,0]],columns = ['shape','radius','weight','usage'])

In [61]:
scaler = StandardScaler()

In [62]:
scaler.fit_transform(nd)

array([[ 0.        , -1.22474487, -0.46830146,  0.        ],
       [ 0.        ,  0.        ,  1.38979787,  0.        ],
       [ 0.        ,  1.22474487, -0.92149641,  0.        ]])

In [63]:
lr.predict(nd)

array([1, 1, 1])