    Shape should be round
    radius of 5.6 length
    usage is play
    weight on a specific range

#### Underfitting

    Shape needs to round

    new object is an orange

#### Regularaization

    -   Ridge regression
    -   Lasso regression

In [55]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression
from sklearn import datasets

In [56]:
for i in dir(datasets):
    if i.startswith("load"):
        print(i)

load_breast_cancer
load_diabetes
load_digits
load_files
load_iris
load_linnerud
load_sample_image
load_sample_images
load_svmlight_file
load_svmlight_files
load_wine


In [57]:
x,y = datasets.make_regression(n_samples = 40 , n_features = 5 , n_informative = 3 , n_targets = 1 , random_state = 42)

In [58]:
x.shape

(40, 5)

In [59]:
y.shape

(40,)

In [60]:
x

array([[-0.11564828,  0.73846658,  0.17136828, -0.3011037 , -1.47852199],
       [ 0.17457781,  0.40405086,  1.8861859 ,  0.25755039, -0.07444592],
       [ 0.24196227, -0.46341769, -0.46572975, -1.91328024, -1.72491783],
       [ 0.32875111, -0.50175704,  0.91540212, -0.5297602 ,  0.51326743],
       [-1.0708925 ,  0.62566735, -0.85715756,  0.48247242, -0.22346279],
       [ 1.15859558, -0.97468167,  0.7870846 , -0.82068232,  0.96337613],
       [-0.68002472,  0.25049285,  0.34644821,  0.2322537 ,  0.29307247],
       [-1.32045661,  0.78182287, -1.23695071,  0.52194157,  0.29698467],
       [-1.06230371, -1.55066343,  0.06856297,  0.47359243, -0.91942423],
       [-0.32206152,  1.54993441, -0.78325329,  0.81351722, -1.23086432],
       [ 0.0675282 ,  1.46564877, -0.2257763 , -1.42474819, -0.54438272],
       [ 0.06023021, -1.91877122, -0.02651388,  2.46324211, -0.19236096],
       [-0.676922  ,  0.32408397, -0.38508228,  0.61167629,  1.03099952],
       [ 0.47383292, -0.71435142,  1.8

In [61]:
y

array([  69.42462633,  187.34141479,  -58.29366785,   46.7017741 ,
        -83.24406634,   53.54474788,    0.24257077, -115.07229782,
       -205.01634481,   55.51793051,  116.57409864, -166.11374379,
        -47.27396104,  108.56235121, -179.22864429,  -49.34319955,
        -23.59678382,  110.19189996,  -20.95179396,  149.93199197,
        143.14366808,   31.3372981 ,   -2.0111799 ,   92.62414894,
         57.71840316,  183.60638683, -228.23366705,   78.48308734,
        -88.27323635,  229.32138046, -102.45741085,  174.85158336,
         83.47805936, -132.90778083,  -57.573086  ,   99.81541576,
       -143.85037699,   79.33701253,    4.7416435 ,   39.18598657])

In [62]:
xtrain,xtest,ytrain,ytest = tts(x,y,test_size = 0.2 , random_state = 42)

In [63]:
xtrain

array([[ 0.21409374, -0.44651495,  0.85639879, -1.24573878,  0.17318093],
       [-0.68002472,  0.25049285,  0.34644821,  0.2322537 ,  0.29307247],
       [ 1.0035329 ,  1.35624003, -0.07201012,  0.36163603, -0.64511975],
       [-0.32206152,  1.54993441, -0.78325329,  0.81351722, -1.23086432],
       [ 0.47383292, -0.71435142,  1.86577451, -1.1913035 ,  0.65655361],
       [ 1.45353408,  0.82718325,  0.01300189, -0.26465683,  2.72016917],
       [-1.16867804,  0.30154734, -0.03471177,  1.14282281,  0.75193303],
       [-1.06230371, -1.55066343,  0.06856297,  0.47359243, -0.91942423],
       [ 1.47789404, -0.21967189,  0.35711257, -0.51827022, -0.8084936 ],
       [-0.29900735,  0.8219025 ,  0.08704707,  0.09176078, -1.98756891],
       [-0.11564828,  0.73846658,  0.17136828, -0.3011037 , -1.47852199],
       [-1.10633497, -0.47917424, -0.18565898, -1.19620662,  0.81252582],
       [ 1.15859558, -0.97468167,  0.7870846 , -0.82068232,  0.96337613],
       [ 0.06023021, -1.91877122, -0.0

In [64]:
xtest

array([[ 0.76743473, -0.23413696,  1.57921282, -0.46947439,  0.54256004],
       [ 1.05712223, -0.71984421, -0.46063877,  0.34361829, -1.76304016],
       [ 0.37569802,  0.11092259, -1.15099358, -0.60063869, -0.29169375],
       [-1.95967012, -1.22084365,  0.2088636 , -1.32818605,  0.19686124],
       [-1.0708925 ,  0.62566735, -0.85715756,  0.48247242, -0.22346279],
       [-0.676922  ,  0.32408397, -0.38508228,  0.61167629,  1.03099952],
       [-0.56629773,  2.19045563, -0.99053633,  0.09965137, -0.50347565],
       [ 0.64768854,  0.49671415, -0.1382643 ,  1.52302986, -0.23415337]])

In [65]:
ytrain

array([  39.18598657,    0.24257077,  183.60638683,   55.51793051,
        108.56235121,  174.85158336,  -57.573086  , -205.01634481,
        110.19189996,   57.71840316,   69.42462633, -132.90778083,
         53.54474788, -166.11374379,  187.34141479,  229.32138046,
         31.3372981 ,  -58.29366785, -102.45741085, -143.85037699,
         46.7017741 ,   99.81541576,   92.62414894,   83.47805936,
        116.57409864,   -2.0111799 ,  -20.95179396,  143.14366808,
       -115.07229782, -179.22864429,  -88.27323635,    4.7416435 ])

In [66]:
ytest

array([ 149.93199197,  -23.59678382,  -49.34319955, -228.23366705,
        -83.24406634,  -47.27396104,   79.33701253,   78.48308734])

In [67]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [68]:
ypred = lr.predict(xtest)

In [69]:
ypred

array([ 149.93199197,  -23.59678382,  -49.34319955, -228.23366705,
        -83.24406634,  -47.27396104,   79.33701253,   78.48308734])

In [70]:
ytest

array([ 149.93199197,  -23.59678382,  -49.34319955, -228.23366705,
        -83.24406634,  -47.27396104,   79.33701253,   78.48308734])

In [71]:
lr.score(xtest,ytest)

1.0

In [72]:
lr.score(xtrain,ytrain)

1.0

In [73]:
from sklearn.linear_model import Ridge,Lasso

In [74]:
lmodel = Lasso()
lmodel.fit(xtrain,ytrain)

Lasso()

In [75]:
lpred = lmodel.predict(xtest)

In [76]:
ypred

array([ 149.93199197,  -23.59678382,  -49.34319955, -228.23366705,
        -83.24406634,  -47.27396104,   79.33701253,   78.48308734])

In [77]:
lpred

array([ 147.3681902 ,  -22.81700993,  -47.88695805, -224.0445553 ,
        -81.18115721,  -45.96270977,   78.76565073,   77.56625987])

In [78]:
lmodel.score(xtest,ytest)

0.9996504994401076

In [79]:
lmodel.score(xtrain,ytrain)

0.9996875144021128

In [80]:
rmodel = Ridge()
rmodel.fit(xtrain,ytrain)

Ridge()

In [81]:
rpred = rmodel.predict(xtest)

In [82]:
ypred

array([ 149.93199197,  -23.59678382,  -49.34319955, -228.23366705,
        -83.24406634,  -47.27396104,   79.33701253,   78.48308734])

In [83]:
rpred

array([ 144.32871019,  -21.6671218 ,  -45.68216229, -217.31300573,
        -79.42757839,  -45.31104986,   76.8190408 ,   74.75205807])

In [84]:
rmodel.score(xtrain,ytrain)

0.9982631627517605

In [93]:
alpha_lst = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5]

In [94]:
for i in alpha_lst:
    r1model = Ridge(alpha = i)
    ridge_model = r1model.fit(xtrain,ytrain)
    rmpred = ridge_model.predict(xtest)
    print(f"the ridge model score is {ridge_model.score(xtest,ytest)} while the alpha value is {i} and the difference in test data with each alpha value is {ypred-rmpred}")

the ridge model score is 0.9999769298748313 while the alpha value is 0.1 and the difference in test data with each alpha value is [ 0.58355896 -0.20089658 -0.38331593 -1.13851074 -0.3956711  -0.20134747
  0.26161879  0.39271013]
the ridge model score is 0.9999085853392856 while the alpha value is 0.2 and the difference in test data with each alpha value is [ 1.16176228 -0.39997015 -0.76265422 -2.26630262 -0.78811908 -0.40154821
  0.52097993  0.78087155]
the ridge model score is 0.9997962374523289 while the alpha value is 0.3 and the difference in test data with each alpha value is [ 1.73468481 -0.59724409 -1.13807407 -3.38352994 -1.17738533 -0.60061102
  0.77811241  1.16455879]
the ridge model score is 0.9996411212788289 while the alpha value is 0.4 and the difference in test data with each alpha value is [ 2.30240002 -0.79274144 -1.50963356 -4.490344   -1.56351053 -0.7985446
  1.03304472  1.54384477]
the ridge model score is 0.9994444370299507 while the alpha value is 0.5 and the diff

In [95]:
for i in alpha_lst:
    l1model = Lasso(alpha = i)
    lasso_model = l1model.fit(xtrain,ytrain)
    lmpred = lasso_model.predict(xtest)
    print(f"the lasso model score is {lasso_model.score(xtest,ytest)} while the alpha value is {i} and the difference in test data with each alpha value is {ypred-lmpred}")

the lasso model score is 0.9999965052850907 while the alpha value is 0.1 and the difference in test data with each alpha value is [ 0.25636239 -0.07803489 -0.14564109 -0.41889186 -0.2062474  -0.13109885
  0.05721343  0.09167804]
the lasso model score is 0.9999860228948431 while the alpha value is 0.2 and the difference in test data with each alpha value is [ 0.51270643 -0.15609171 -0.29129368 -0.83770949 -0.41246902 -0.26218001
  0.11441925  0.18333226]
the lasso model score is 0.9999685490233102 while the alpha value is 0.3 and the difference in test data with each alpha value is [ 0.76909066 -0.23405824 -0.43691433 -1.25662833 -0.6187687  -0.39331056
  0.17154307  0.27501722]
the lasso model score is 0.999944084566349 while the alpha value is 0.4 and the difference in test data with each alpha value is [ 1.02547796 -0.31201762 -0.58253249 -1.67555453 -0.82507447 -0.52444495
  0.22866003  0.3667044 ]
the lasso model score is 0.9999126297101272 while the alpha value is 0.5 and the diff