#### Recurrent Neural Network RNN

-   Sequential scnearios
-   With RNN the feedback learning or the feedback loop works more efficiently
-   With each epoch running the model is constantly reciving feedbacks on the output layer

-   RNN is designed to handle Sequential data more efficiently than ANN
-   RNN processes input sequence of one element at a time 
-   RNN is more used into time series prediction

In [2]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import SimpleRNN , Dense

In [15]:
np.random.seed(0)
xtrain = np.random.rand(100,10,1) 
ytrain = np.random.rand(100,1)
xtest = np.random.rand(20,10,1)
ytest = np.random.rand(20,1)

In [16]:
xtrain

array([[[5.48813504e-01],
        [7.15189366e-01],
        [6.02763376e-01],
        [5.44883183e-01],
        [4.23654799e-01],
        [6.45894113e-01],
        [4.37587211e-01],
        [8.91773001e-01],
        [9.63662761e-01],
        [3.83441519e-01]],

       [[7.91725038e-01],
        [5.28894920e-01],
        [5.68044561e-01],
        [9.25596638e-01],
        [7.10360582e-02],
        [8.71292997e-02],
        [2.02183974e-02],
        [8.32619846e-01],
        [7.78156751e-01],
        [8.70012148e-01]],

       [[9.78618342e-01],
        [7.99158564e-01],
        [4.61479362e-01],
        [7.80529176e-01],
        [1.18274426e-01],
        [6.39921021e-01],
        [1.43353287e-01],
        [9.44668917e-01],
        [5.21848322e-01],
        [4.14661940e-01]],

       [[2.64555612e-01],
        [7.74233689e-01],
        [4.56150332e-01],
        [5.68433949e-01],
        [1.87898004e-02],
        [6.17635497e-01],
        [6.12095723e-01],
        [6.16933997e-01],
      

In [17]:
ytrain

array([[5.92880271e-01],
       [1.00636957e-02],
       [4.75826196e-01],
       [7.08770391e-01],
       [4.39754320e-02],
       [8.79521483e-01],
       [5.20081417e-01],
       [3.06610483e-02],
       [2.24413612e-01],
       [9.53675696e-01],
       [5.82319733e-01],
       [1.07472568e-01],
       [2.87544502e-01],
       [4.56703626e-01],
       [2.09500693e-02],
       [4.11615514e-01],
       [4.89458635e-01],
       [2.43677875e-01],
       [5.88639000e-01],
       [7.53240120e-01],
       [2.35834224e-01],
       [6.20499900e-01],
       [6.39622243e-01],
       [9.48540301e-01],
       [7.78276167e-01],
       [8.48345270e-01],
       [4.90419908e-01],
       [1.85348587e-01],
       [9.95815293e-01],
       [1.29355761e-01],
       [4.71457319e-01],
       [6.80930992e-02],
       [9.43850857e-01],
       [9.64924941e-01],
       [7.19389062e-01],
       [3.49992844e-01],
       [2.54382401e-01],
       [2.65303325e-01],
       [1.27294025e-01],
       [5.25808953e-01],


In [18]:
xtest

array([[[0.29594983],
        [0.92929167],
        [0.26590563],
        [0.82814661],
        [0.98510868],
        [0.78339665],
        [0.51898992],
        [0.06607426],
        [0.47241379],
        [0.43825595]],

       [[0.20279604],
        [0.42358764],
        [0.35775788],
        [0.16368426],
        [0.44137414],
        [0.26279996],
        [0.52206242],
        [0.03516006],
        [0.90623142],
        [0.81636431]],

       [[0.55258133],
        [0.85180858],
        [0.96239507],
        [0.11052229],
        [0.63083181],
        [0.997994  ],
        [0.98788917],
        [0.60332299],
        [0.12802087],
        [0.58319283]],

       [[0.00206464],
        [0.19891133],
        [0.95612316],
        [0.33044057],
        [0.63839011],
        [0.28085949],
        [0.94782189],
        [0.72855873],
        [0.32965116],
        [0.79176142]],

       [[0.10816552],
        [0.39231894],
        [0.22121813],
        [0.68372645],
        [0.10244628],
  

In [19]:
ytest

array([[0.86711454],
       [0.29426616],
       [0.43535347],
       [0.79545653],
       [0.67750836],
       [0.93786437],
       [0.62114033],
       [0.09781016],
       [0.88436036],
       [0.76915552],
       [0.71187045],
       [0.05373355],
       [0.39622274],
       [0.16743582],
       [0.82190391],
       [0.70052862],
       [0.8830776 ],
       [0.96657511],
       [0.77474761],
       [0.99423308]])

In [20]:
# Building the model 
model = Sequential([
    SimpleRNN(64,input_shape=(10,1),activation='relu',return_sequences=False),Dense(1)
])

In [21]:
model.compile(
    optimizer = 'adam',
    loss = 'mse',
    metrics = ['mae']
)

-   MSE (mean squared error)  - Squared up values of all the error , then finding the mean of all these squared up errors.
-   MAE (mean absolute error) - The mean value of all errors in it's absolute form

In [22]:
model.fit(xtrain,ytrain,epochs=10,batch_size=32,verbose=0)

In [23]:
test_loss , test_mae = model.evaluate(xtest,ytest,verbose=0)
print('Test MAE',test_mae)

Test MAE 0.27624407410621643


In [14]:
xnew = np.random.rand(5,10,1) # 5 new sequence
prediction = model.predict(xnew)
print('prediction for new data:')
print(prediction)

1/1 [==============================] - 0s 315ms/step
prediction for new data:
[[0.5917321 ]
 [0.5089938 ]
 [0.49525678]
 [0.3911422 ]
 [0.5619582 ]]
