#### Artifical Neural Network - ANN

These Network consists of interconnected nodes - Neurons.
These Neurons are organized in Layers 

The Typical Layers of ANN -

-   Input Layer - Receives the input data
-   Hidden Layer - Perform computation on the input data
-   Output Layer - Produces the final output 

Activation Functions -

-   Sigmoid Function - Output layer of the binary Classification problem (0,1)
-   Rectified Linear Unit (Relu) - Used in the hidden layers  for activation function, it's less complex  and faster compared to sigmoid functions. It is also used as a normalization technique.
-   Softmax Function - Output layer of the multiclass classification 
-   Tanh (Hyperbolic Tangent) - Similar to sigmoid function , often used in Hidden Layers (-1,1)


Sequential Model -

-   Allows you to create model layers one on the top of another
-   Minimizes the loss and improves the accuracy with each model
-   Used for building Simple neural networks

Hyper Parameter tuning in ANN -

-   Optimizer - Minimizing the loss function by adjusting the coffecient weights
-   Adam (Adaptive Momemnt estimation)
-   Loss Function - the function which determines and reduces the difference between actual value and predicted value - (Binary Cross Entropy)


Epochs - A complete  pass through all the training dataset is called an Epoch . In simple words it's how many times we are going through our entire Training Set while updatingModel Evaluation Metrics.

Batch Size - anything greater than 1 
    -   Reduces memory requirements
    -   Noise Optimization
    -   It allows dor GPU Optimaztion


Verbose = 0,1,2 

-   0 - During training no output or progress will be shown
-   1 - Default mode - progress bars will be displayed during training
-   2 - One line per epoch will be printed , displaying the progress.

In [14]:
import numpy as np 
import tensorflow as tf 
from tensorflow import keras

In [15]:
np.random.seed(0)
xtrain = np.random.rand(1000,10) # 1000 samples with 10 features
ytrain = np.random.randint(2,size=1000) # binary labels (0,1)
xtest = np.random.rand(200,10) # 200 samples for testing
ytest = np.random.randint(2,size=200)

In [16]:
xtrain

array([[0.5488135 , 0.71518937, 0.60276338, ..., 0.891773  , 0.96366276,
        0.38344152],
       [0.79172504, 0.52889492, 0.56804456, ..., 0.83261985, 0.77815675,
        0.87001215],
       [0.97861834, 0.79915856, 0.46147936, ..., 0.94466892, 0.52184832,
        0.41466194],
       ...,
       [0.40931658, 0.8162211 , 0.01154924, ..., 0.3767429 , 0.69770858,
        0.84842039],
       [0.47831657, 0.84636004, 0.54831934, ..., 0.76534181, 0.52550272,
        0.9910432 ],
       [0.69498333, 0.19460689, 0.11403676, ..., 0.75842952, 0.02378743,
        0.81357508]])

In [17]:
ytrain

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,

In [18]:
xtest

array([[0.73493626, 0.54970556, 0.59751899, ..., 0.80721426, 0.70350412,
        0.56494766],
       [0.10496093, 0.0660424 , 0.38398149, ..., 0.49670186, 0.02509595,
        0.6952865 ],
       [0.91840767, 0.5996943 , 0.58041268, ..., 0.81926978, 0.73483397,
        0.84438803],
       ...,
       [0.23141815, 0.47711054, 0.07483832, ..., 0.92292677, 0.91095714,
        0.25647738],
       [0.54906972, 0.43266834, 0.04591842, ..., 0.20341135, 0.07320846,
        0.16904787],
       [0.00991494, 0.75578646, 0.20456619, ..., 0.27313124, 0.95002678,
        0.3104168 ]])

In [19]:
ytest

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0])

In [20]:
# Building the ANN Model - 

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(10,)),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

In [27]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(xtrain,ytrain,epochs=25,batch_size=10,verbose=1)

Epoch 1/25
100/100 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7370
Epoch 2/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5472 - accuracy: 0.7300
Epoch 3/25
100/100 [==============================] - 0s 4ms/step - loss: 0.5467 - accuracy: 0.7230
Epoch 4/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5367 - accuracy: 0.7420
Epoch 5/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5364 - accuracy: 0.7270
Epoch 6/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5329 - accuracy: 0.7410
Epoch 7/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5325 - accuracy: 0.7290
Epoch 8/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5292 - accuracy: 0.7450
Epoch 9/25
100/100 [==============================] - 0s 3ms/step - loss: 0.5327 - accuracy: 0.7400
Epoch 10/25
100/100 [==============================] - 0s 4ms/step - loss: 0.5260 - accuracy: 0.7480

In [28]:
test_loss,test_acc = model.evaluate(xtest,ytest,verbose=1)
print('test accuracy',test_acc)

7/7 [==============================] - 0s 5ms/step - loss: 0.8569 - accuracy: 0.4850
test accuracy 0.48500001430511475
