In [2]:
import pandas as pd
import numpy as np

In [6]:
myar1 = np.array([4,23,46,177])
myar2 = np.array([45,23,75,9])
print(myar1<myar2)

[ True False  True False]


In [16]:
myar3 = np.array([[12,13,14],[75,76,77],[75,14,16]])
print(myar3)

[[12 13 14]
 [75 76 77]
 [75 14 16]]


In [17]:
print(np.ndim(myar3))

2


In [20]:
print(myar3[1])

[75 76 77]


In [21]:
print(myar3.transpose())

[[12 75 75]
 [13 76 14]
 [14 77 16]]


In [22]:
pricelist = [100,200,300,400]
productseries = pd.Series(pricelist,index = ['pen','shirt','book','mouse'])

In [23]:
print(productseries)

pen      100
shirt    200
book     300
mouse    400
dtype: int64


In [24]:
productdf = pd.DataFrame([[100,200,300,400],[800,750,130,540]],columns=['pen','shirt','book','mouse'])

In [25]:
print(productdf)

   pen  shirt  book  mouse
0  100    200   300    400
1  800    750   130    540


In [31]:
productdf.size

16

In [28]:
prow = pd.DataFrame([[190,230,360,800],[450,650,190,590]],columns=['pen','shirt','book','mouse'])
print(prow)

   pen  shirt  book  mouse
0  190    230   360    800
1  450    650   190    590


In [29]:
productdf = productdf.append(prow)

C:\Users\sengu\AppData\Local\Temp\ipykernel_16240\2142426078.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  productdf = productdf.append(prow)


In [30]:
productdf

pen  shirt  book  mouse
0  100    200   300    400
1  800    750   130    540
0  190    230   360    800
1  450    650   190    590

In [33]:
productdf.shape

(4, 4)

In [34]:
productdf.reset_index()

index  pen  shirt  book  mouse
0      0  100    200   300    400
1      1  800    750   130    540
2      0  190    230   360    800
3      1  450    650   190    590

In [35]:
productdf['mobile']=[150,250,630,100]

In [36]:
productdf

pen  shirt  book  mouse  mobile
0  100    200   300    400     150
1  800    750   130    540     250
0  190    230   360    800     630
1  450    650   190    590     100

In [37]:
productdf.drop(columns='mobile')

pen  shirt  book  mouse
0  100    200   300    400
1  800    750   130    540
0  190    230   360    800
1  450    650   190    590

In [38]:
productdf.drop(index=[0])

pen  shirt  book  mouse  mobile
1  800    750   130    540     250
1  450    650   190    590     100