#### Mean Squared Error (MSE)

    -   there is a training data
    -   there is a test data
    -   We build the model with training data
    -   Test our model with testing data

In [1]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse

In [2]:
df = pd.read_csv(r'D:\DS WorkFlow\Datasets\boston_house_prices.csv')

In [3]:
df.head()

506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0     CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1  0.00632  18       2.31          0      0.538      6.575       65.2   
2  0.02731   0       7.07          0      0.469      6.421       78.9   
3  0.02729   0       7.07          0      0.469      7.185       61.1   
4  0.03237   0       2.18          0      0.458      6.998       45.8   

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0        DIS        RAD        TAX     PTRATIO           B       LSTAT   
1       4.09          1        296        15.3       396.9        4.98   
2     4.9671          2        242        17.8       396.9        9.14   
3     4.9671          2        242        17.8      392.83        4.03   
4     6.0622          3        222        18.7      394.63        2.94   

  Unnamed: 13  
0        MEDV  
1          24  
2        21.6  
3        34.7  
4        33.4

In [4]:
df.isnull().sum()

506            0
13             0
Unnamed: 2     0
Unnamed: 3     0
Unnamed: 4     0
Unnamed: 5     0
Unnamed: 6     0
Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
dtype: int64

In [5]:
df.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']

In [6]:
df.drop([0],axis=0,inplace=True)

In [7]:
#train and test split
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [8]:
x

CRIM  ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD  TAX PTRATIO  \
1    0.00632  18   2.31    0  0.538  6.575  65.2    4.09   1  296    15.3   
2    0.02731   0   7.07    0  0.469  6.421  78.9  4.9671   2  242    17.8   
3    0.02729   0   7.07    0  0.469  7.185  61.1  4.9671   2  242    17.8   
4    0.03237   0   2.18    0  0.458  6.998  45.8  6.0622   3  222    18.7   
5    0.06905   0   2.18    0  0.458  7.147  54.2  6.0622   3  222    18.7   
..       ...  ..    ...  ...    ...    ...   ...     ...  ..  ...     ...   
502  0.06263   0  11.93    0  0.573  6.593  69.1  2.4786   1  273      21   
503  0.04527   0  11.93    0  0.573   6.12  76.7  2.2875   1  273      21   
504  0.06076   0  11.93    0  0.573  6.976    91  2.1675   1  273      21   
505  0.10959   0  11.93    0  0.573  6.794  89.3  2.3889   1  273      21   
506  0.04741   0  11.93    0  0.573   6.03  80.8   2.505   1  273      21   

          B LSTAT  
1     396.9  4.98  
2     396.9  9.14  
3    392.83  4.03  
4    394.63  2.94  
5     396.9  5.33  
..      ...   ...  
502  391.99  9.67  
503   396.9  9.08  
504   396.9  5.64  
505  393.45  6.48  
506   396.9  7.88  

[506 rows x 13 columns]

In [9]:
x.shape

(506, 13)

In [10]:
y.shape

(506,)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
y

1        24
2      21.6
3      34.7
4      33.4
5      36.2
       ... 
502    22.4
503    20.6
504    23.9
505      22
506    11.9
Name: MEDV, Length: 506, dtype: object

In [13]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [14]:
x

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [15]:
xtrain , xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [16]:
xtrain

array([[-0.40546803, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.38983794, -0.48772236, -0.37597609, ...,  1.13022958,
         0.37888402,  0.40607459],
       [-0.34935053,  0.370669  , -1.04569998, ..., -2.52243411,
         0.36210855, -1.05593797],
       ...,
       [-0.41899176,  3.37503876, -1.44695069, ..., -0.2568579 ,
         0.4304165 , -1.09939185],
       [-0.4083343 ,  1.22906036, -0.68968118, ..., -0.39556665,
         0.35717459, -0.92557636],
       [-0.38264608, -0.48772236,  1.56899549, ...,  1.26893833,
         0.44105193,  0.38364678]])

In [17]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [18]:
lr.score(xtest,ytest)

0.6994217129497193

In [19]:
ypred = lr.predict(xtest)

In [20]:
ypred

array([21.05157024, 19.71643082, 30.4550923 , 20.66406522, 22.48354729,
       20.42503177, 16.40115024, 30.57355152,  8.11480223, 23.96729455,
       24.53889219, 23.22223925, 13.63384925,  7.35789081, 15.0752372 ,
       22.98007417, 27.87262959, 10.9980466 , 23.35470211, 15.79626054,
       27.01513729, 25.60393122, 27.35042753,  3.38721208, 22.09214375,
       28.65462948, 36.61354935,  6.35602558, 27.13422253, 20.93790046,
       31.50206084, 31.78702053, 18.89927911, 16.95645935, 33.87039494,
       17.32847031, 28.91495478, 25.07229945, 15.27897477, 29.12481131,
       32.02266075, 21.85762164,  9.09946742, 17.38097862, 13.39604145,
       27.59557476, 20.84225188, 12.77973676, 20.22526685, 21.01178003,
       18.67593315, 21.19002068, 22.48179868, 32.93055394, 23.10095884,
       28.30927175, 23.47571647, 37.12634126, 22.47053118, 21.83560079,
       24.12537211, 20.99112842, 14.05756609, 26.35280975, 20.21008773,
       27.58064   , 18.7865955 , 17.06626463, 34.27359912, 19.22

In [21]:
ytest

72     21.7
287    20.1
220      23
30       21
37       20
       ... 
468    19.1
392    23.2
90     28.7
242    20.1
253    29.6
Name: MEDV, Length: 102, dtype: object

In [22]:
mse_sklearn = mse(ytest,ypred)

In [23]:
print(mse_sklearn)

15.856591219120299


In [24]:
print(type(ypred))

<class 'numpy.ndarray'>


In [28]:
ypred_lst = []
for i in ypred:
    ypred_lst.append(float(i))
    

In [29]:
ytest_lst = []
for i in ytest:
    ytest_lst.append(float(i))

In [36]:
print(ypred_lst[0])

21.051570238128452


In [37]:
print(ytest_lst[0])

21.7


In [42]:
changes = 

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [44]:
subtracted = []
for i, j in zip(ypred_lst, ytest_lst):
    item = i - j
    subtracted.append(item)

print(subtracted)

[-0.6484297618715473, -0.3835691815182365, 7.45509230217575, -0.33593478209219185, 2.483547286367987, 7.325031774487025, 3.001150239564234, -4.126448477680881, -3.6851977723868163, 1.1672945464008357, 0.6388921925547493, -2.9777607526765912, -6.066150745084277, -1.1421091861367003, 3.375237197390966, 3.1800741733812075, 1.2726295870025481, -1.7019534012633546, -1.045297891011316, -4.303739464193724, 3.315137286817901, -0.8960687797782505, 5.050427532469566, -5.412787920152873, 0.9921437518321028, 2.2546294774905675, 4.21354935393817, -3.843974415819684, 5.034222526113812, -0.26209954356602694, 0.8020608419803885, 2.787020534783661, -1.0007208857657623, 6.756459347209937, 2.2703949359386115, -2.671529691537774, 0.5149547846633666, 0.3722994517416254, 4.878974772753304, 6.324811314852219, 0.9226607467007781, -3.1423783639538456, -14.60053257869355, -2.0190213849013006, 0.09604144977332929, 5.295574757839962, 4.642251875708713, 3.2797367635012282, -3.8747331542660497, -0.7882199708433681,

In [45]:
print(len(subtracted))

102


In [47]:
sq_error_lst = []
for i in subtracted:
    sq_error_lst.append(np.square(i))

In [48]:
sq_error_lst

[0.4204611560807916,
 0.14712531701056986,
 55.57840123396012,
 0.11285217781932842,
 6.168007123625791,
 53.656090497244534,
 9.00690276043646,
 17.027577038954863,
 13.580682621604753,
 1.362576558057133,
 0.4081832337074148,
 8.86705910018106,
 36.798184862086536,
 1.3044133930578359,
 11.392226138651623,
 10.11287174820617,
 1.6195860657142762,
 2.8966453800719014,
 1.092647680952705,
 18.52217337565848,
 10.990135230450354,
 0.8029392580932828,
 25.506818260726632,
 29.298273068552863,
 0.9843492242994811,
 5.083354080769389,
 17.75399815807277,
 14.77613930947628,
 25.34339644243173,
 0.06869617073751966,
 0.6433015942382898,
 7.767483461305804,
 1.001442291207812,
 45.64974291050053,
 5.154693165135692,
 7.137070892767915,
 0.26517843024769433,
 0.13860688176711483,
 23.80439483316316,
 40.00323816848266,
 0.8513028535024375,
 9.874541782245247,
 213.1755515814917,
 4.076447352688766,
 0.009223960074562932,
 28.04311201587177,
 21.55050247752106,
 10.756673237861511,
 15.0135570

In [49]:
print(np.mean(sq_error_lst))

15.856591219120299


In [50]:
from sklearn.metrics import mean_absolute_error

In [51]:
mae = mean_absolute_error(ytest,ypred)

In [52]:
print(mae)

3.046358124884449


In [53]:
abs_error_lst = []
for i in subtracted:
    abs_error_lst.append(np.abs(i))

In [54]:
mae1 = np.mean(abs_error_lst)

In [55]:
print(mae1)

3.046358124884449


In [56]:
#RMSE - root mean squared error
rmse = np.sqrt(mse_sklearn)
print(rmse)

3.982033553238885


In [58]:
rmse = mse(ytest,ypred,squared=False)

In [59]:
print(rmse)

3.982033553238885
