#### Mean Squared Error (MSE)

    -   there is a training data
    -   there is a test data
    -   We build the model with training data
    -   Test our model with testing data

In [15]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse

In [16]:
df = pd.read_csv(r'D:\DS WorkFlow\Datasets\boston_house_prices.csv')

In [17]:
df.head()

506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0     CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1  0.00632  18       2.31          0      0.538      6.575       65.2   
2  0.02731   0       7.07          0      0.469      6.421       78.9   
3  0.02729   0       7.07          0      0.469      7.185       61.1   
4  0.03237   0       2.18          0      0.458      6.998       45.8   

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0        DIS        RAD        TAX     PTRATIO           B       LSTAT   
1       4.09          1        296        15.3       396.9        4.98   
2     4.9671          2        242        17.8       396.9        9.14   
3     4.9671          2        242        17.8      392.83        4.03   
4     6.0622          3        222        18.7      394.63        2.94   

  Unnamed: 13  
0        MEDV  
1          24  
2        21.6  
3        34.7  
4        33.4

In [18]:
df.isnull().sum()

506            0
13             0
Unnamed: 2     0
Unnamed: 3     0
Unnamed: 4     0
Unnamed: 5     0
Unnamed: 6     0
Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
dtype: int64

In [19]:
df.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']

In [20]:
df.drop([0],axis=0,inplace=True)

In [21]:
#train and test split
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [22]:
x

CRIM  ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD  TAX PTRATIO  \
1    0.00632  18   2.31    0  0.538  6.575  65.2    4.09   1  296    15.3   
2    0.02731   0   7.07    0  0.469  6.421  78.9  4.9671   2  242    17.8   
3    0.02729   0   7.07    0  0.469  7.185  61.1  4.9671   2  242    17.8   
4    0.03237   0   2.18    0  0.458  6.998  45.8  6.0622   3  222    18.7   
5    0.06905   0   2.18    0  0.458  7.147  54.2  6.0622   3  222    18.7   
..       ...  ..    ...  ...    ...    ...   ...     ...  ..  ...     ...   
502  0.06263   0  11.93    0  0.573  6.593  69.1  2.4786   1  273      21   
503  0.04527   0  11.93    0  0.573   6.12  76.7  2.2875   1  273      21   
504  0.06076   0  11.93    0  0.573  6.976    91  2.1675   1  273      21   
505  0.10959   0  11.93    0  0.573  6.794  89.3  2.3889   1  273      21   
506  0.04741   0  11.93    0  0.573   6.03  80.8   2.505   1  273      21   

          B LSTAT  
1     396.9  4.98  
2     396.9  9.14  
3    392.83  4.03  
4    394.63  2.94  
5     396.9  5.33  
..      ...   ...  
502  391.99  9.67  
503   396.9  9.08  
504   396.9  5.64  
505  393.45  6.48  
506   396.9  7.88  

[506 rows x 13 columns]

In [23]:
x.shape

(506, 13)

In [24]:
y.shape

(506,)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
y

1        24
2      21.6
3      34.7
4      33.4
5      36.2
       ... 
502    22.4
503    20.6
504    23.9
505      22
506    11.9
Name: MEDV, Length: 506, dtype: object

In [27]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [28]:
x

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [29]:
xtrain , xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [30]:
xtrain

array([[-0.38194318, -0.48772236, -0.72032214, ..., -0.48803915,
         0.2442417 , -1.2199413 ],
       [-0.40616976, -0.48772236, -0.16440754, ..., -0.30309415,
         0.41967143,  0.49858928],
       [-0.41547031,  0.41358857, -0.80203138, ..., -0.76545664,
         0.40892636, -0.45178897],
       ...,
       [ 0.62485868, -0.48772236,  1.01599907, ...,  0.80657583,
         0.23086518,  0.69343084],
       [-0.28941366, -0.48772236,  1.2319449 , ..., -1.73641788,
        -0.14685696, -0.07472149],
       [-0.2770909 , -0.48772236, -0.43725801, ...,  1.17646583,
         0.44105193,  0.85042548]])

In [31]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [32]:
lr.score(xtest,ytest)

0.7263390279537018

In [33]:
ypred = lr.predict(xtest)

In [34]:
ypred

array([30.63296159, 18.94369916, 18.8758913 , 24.93085624, 17.38977425,
       19.1855544 , 24.73270927, 21.66523743, 19.46959516,  8.29710665,
        4.46176761, 16.3130851 , 17.23534119, 22.5186506 , 21.3474422 ,
       20.23320317, 20.97109046, 17.88697013, 23.96635205, 25.60975643,
       21.94108561, 25.23662634, 13.06452826, 18.79122158, 23.16346652,
       36.58418148, 21.18152292, 20.51768701, 27.71823881, 16.82754972,
       23.15416727, 17.70525912, 32.04185541, 42.45863772, 28.67812641,
       30.32428064, 11.09114   ,  5.53971157, 12.70453759, 16.98794231,
       25.91277041, 13.99677911, 24.05392167, 42.37166192, 24.29060161,
        9.62353547, 27.32906108, 28.45627204, 21.95790453, 15.0796978 ,
       23.50997952, 20.07134627, 16.0283482 , 28.16082105, 18.00172246,
       25.15258193,  6.19268044, 30.65077871, 17.47650506, 22.39830314,
       27.50719202, 13.59918795, 21.82790421, 18.21390149, 22.96997017,
       23.47653717, 25.30882234,  3.10894083, 26.95718355,  8.89

In [35]:
ytest

191      37
479    14.6
461    16.4
325      25
317    17.8
       ... 
187      50
190    34.9
433    16.1
89     23.6
142    14.4
Name: MEDV, Length: 102, dtype: object

In [36]:
mse_sklearn = mse(ytest,ypred)

In [37]:
print(mse_sklearn)

27.17844742367854
