#### Numpy
It is used to work with arrays

Group of elements of same data type (string , integer , float)

In [6]:
import numpy as np

In [7]:
myarray1 = np.array([15,75,45,75])
print(type(myarray1))

<class 'numpy.ndarray'>


In [9]:
#view function
myarray2 = myarray1.view()
print(myarray2)


[15 75 45 75]


In [12]:
#copy function
myarray3 = myarray1.copy()
print(myarray3)

[15 75 45 75]


In [16]:
myarray5 = np.arange(10)
print(myarray5)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
myarray6 = np.arange(10,20,2)
print(myarray6)

[10 12 14 16 18]


In [23]:
#linspace
myarray8 = np.linspace(10,20,6)
print(myarray8)

[10. 12. 14. 16. 18. 20.]


In [26]:
myarray10 = np.ones(8)
print(type(myarray10))

<class 'numpy.ndarray'>


In [27]:
print(myarray10)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [28]:
myarray10[2] = 15

In [29]:
print(myarray10)

[ 1.  1. 15.  1.  1.  1.  1.  1.]


In [30]:
print(myarray10.size)

8


In [31]:
print(len(myarray10))

8


In [34]:
myar1 = np.array([10,75,8,23,69,174,58])
#mean
print(np.mean(myar1))

59.57142857142857


In [35]:
#median
print(np.median(myar1))


58.0


In [36]:
myar2 = np.array([10,75,75,8,23,69,75,174,58,75])
print(myar2)

[ 10  75  75   8  23  69  75 174  58  75]


In [37]:
print(np.mode(myar2))

AttributeError: module 'numpy' has no attribute 'mode'

In [38]:
from scipy import stats as st
print(st.mode(myar2))

ModeResult(mode=array([75]), count=array([4]))


In [42]:
print(np.sum(myar1))

417


In [45]:
print(np.sort(myar1)[::-1])

[174  75  69  58  23  10   8]


In [46]:
myar3 = np.array([12,7,56,23,9,456])

In [48]:
print(myar3)
print(np.flip(myar3))

[ 12   7  56  23   9 456]
[456   9  23  56   7  12]


In [49]:
myar8 = np.array([4,16,64])
print(np.sqrt(myar8))

[2. 4. 8.]


In [50]:
print(np.power(myar8,2))

[  16  256 4096]
