##### Classifying the object

    -   Shape
    -   Radius
    -   Weight
    -   Usage

##### Classifying the Ball

    -   Shape - Round
    -   Radius - 5.6 cm
    -   Weight - 150 gm to 250 gm
    -   Usage - Play

##### New Data

    -   Shape - Round
    -   Radius - 7.6 cm
    -   Weight - 150 gm to 250 gm
    -   Usage - Play

In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [39]:
df = pd.DataFrame(data = [['round',5.6,175,'play','ball'],
                          ['round',5.6,180,'play','ball'],
                          ['triange',8.6,189,'play','boomerang'],
                          ['round',5.6,176,'play','ball'],
                          ['triange',8.7,190,'play','boomerang'],
                          ['round',5.6,165,'play','ball'],
                          ['round',5.6,170,'play','ball'],
                          ['round',5.6,173,'play','ball'],
                          ['round',5.6,192,'play','ball'],
                          ['round',5.6,220,'play','ball'],
                          ['triange',7.6,188,'play','boomerang'],
                          ['round',5.6,205,'play','ball'],
                          ['round',5.6,193,'play','ball'],
                          ['round',5.6,171,'play','ball'],
                          ['round',5.6,165,'play','ball'],
                          ['round',5.6,185,'play','ball']],columns = ['shape','radius','weight','usage','label'])

In [40]:
df.head()

shape  radius  weight usage      label
0    round     5.6     175  play       ball
1    round     5.6     180  play       ball
2  triange     8.6     189  play  boomerang
3    round     5.6     176  play       ball
4  triange     8.7     190  play  boomerang

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [42]:
objlst = df.select_dtypes(include = 'object').columns

In [43]:
for i in objlst:
    df[i] = le.fit_transform(df[i])

In [44]:
df.head()

shape  radius  weight  usage  label
0      0     5.6     175      0      0
1      0     5.6     180      0      0
2      1     8.6     189      0      1
3      0     5.6     176      0      0
4      1     8.7     190      0      1

In [45]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [46]:
x

shape  radius  weight  usage
0       0     5.6     175      0
1       0     5.6     180      0
2       1     8.6     189      0
3       0     5.6     176      0
4       1     8.7     190      0
5       0     5.6     165      0
6       0     5.6     170      0
7       0     5.6     173      0
8       0     5.6     192      0
9       0     5.6     220      0
10      1     7.6     188      0
11      0     5.6     205      0
12      0     5.6     193      0
13      0     5.6     171      0
14      0     5.6     165      0
15      0     5.6     185      0

In [47]:
y

0     0
1     0
2     1
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    0
13    0
14    0
15    0
Name: label, dtype: int32

In [48]:
scaler = StandardScaler()
scaler.fit_transform(x)

array([[-0.48038446, -0.47068369, -0.59388661,  0.        ],
       [-0.48038446, -0.47068369, -0.24709151,  0.        ],
       [ 2.081666  ,  2.318553  ,  0.37713967,  0.        ],
       [-0.48038446, -0.47068369, -0.52452759,  0.        ],
       [ 2.081666  ,  2.41152755,  0.44649869,  0.        ],
       [-0.48038446, -0.47068369, -1.28747681,  0.        ],
       [-0.48038446, -0.47068369, -0.94068171,  0.        ],
       [-0.48038446, -0.47068369, -0.73260465,  0.        ],
       [-0.48038446, -0.47068369,  0.58521673,  0.        ],
       [-0.48038446, -0.47068369,  2.5272693 ,  0.        ],
       [ 2.081666  ,  1.38880743,  0.30778065,  0.        ],
       [-0.48038446, -0.47068369,  1.486884  ,  0.        ],
       [-0.48038446, -0.47068369,  0.65457575,  0.        ],
       [-0.48038446, -0.47068369, -0.87132269,  0.        ],
       [-0.48038446, -0.47068369, -1.28747681,  0.        ],
       [-0.48038446, -0.47068369,  0.09970359,  0.        ]])

In [49]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [50]:
ytest.shape

(4,)

In [51]:
lr = LogisticRegression()

In [52]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [53]:
lr.score(xtest,ytest)

1.0

In [54]:
df.head()

shape  radius  weight  usage  label
0      0     5.6     175      0      0
1      0     5.6     180      0      0
2      1     8.6     189      0      1
3      0     5.6     176      0      0
4      1     8.7     190      0      1

In [55]:
ytest

0     0
1     0
5     0
14    0
Name: label, dtype: int32

In [56]:
ypred = lr.predict(xtest)

In [57]:
ypred

array([0, 0, 0, 0])

In [58]:
xtest

shape  radius  weight  usage
0       0     5.6     175      0
1       0     5.6     180      0
5       0     5.6     165      0
14      0     5.6     165      0

In [59]:
nd = pd.DataFrame(data = [[0,8.6,195,0]],columns = ['shape','radius','weight','usage'])

In [60]:
nd

shape  radius  weight  usage
0      0     8.6     195      0

In [61]:
npred = lr.predict(nd)

In [62]:
npred

array([1])

In [63]:
df.head()

shape  radius  weight  usage  label
0      0     5.6     175      0      0
1      0     5.6     180      0      0
2      1     8.6     189      0      1
3      0     5.6     176      0      0
4      1     8.7     190      0      1

In [64]:
x1 = df[['shape']]
y1 = df[['label']]

In [65]:
scaler.fit_transform(x1)

array([[-0.48038446],
       [-0.48038446],
       [ 2.081666  ],
       [-0.48038446],
       [ 2.081666  ],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446],
       [ 2.081666  ],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446],
       [-0.48038446]])

In [66]:
y1

label
0       0
1       0
2       1
3       0
4       1
5       0
6       0
7       0
8       0
9       0
10      1
11      0
12      0
13      0
14      0
15      0

In [68]:
x1train,x1test,y1train,y1test = train_test_split(x1,y1,test_size = 0.02, random_state= 42)

In [69]:
lr1 = LogisticRegression()

In [70]:
lr1.fit(x1train,y1train)

d:\Anaconda\envs\github1\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [72]:
lr1.score(x1test,y1test)

1.0