In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn import datasets

In [41]:
for i in dir(datasets):
    if i.startswith('load'):
        print(i)

load_breast_cancer
load_diabetes
load_digits
load_files
load_iris
load_linnerud
load_sample_image
load_sample_images
load_svmlight_file
load_svmlight_files
load_wine


In [42]:
x,y = datasets.make_regression(n_samples = 40 , n_features = 8, n_informative = 5, n_targets = 1  ,random_state = 42)

In [43]:
x.shape

(40, 8)

In [44]:
y.shape

(40,)

In [45]:
x

array([[ 0.2766908 , -0.88951443, -0.75373616, -0.07710171,  0.82718325,
        -0.24538812, -0.81581028,  0.34115197],
       [ 0.25049285, -1.23695071,  0.78182287,  0.52194157,  0.34644821,
         0.25988279, -1.32045661,  0.29698467],
       [ 1.57921282,  0.64768854, -0.1382643 , -0.23415337,  0.76743473,
         0.49671415,  1.52302986, -0.23413696],
       [-0.60170661, -1.15099358,  0.11092259, -0.60063869,  1.85227818,
        -0.54438272,  0.37569802, -0.29169375],
       [-1.51936997, -1.26088395,  0.40498171,  2.1221562 , -0.48423407,
         1.76545424,  0.91786195,  1.03246526],
       [-1.1913035 ,  0.29307247,  0.2322537 ,  1.86577451,  0.65655361,
        -0.68002472, -0.71435142,  0.47383292],
       [ 0.74729361,  0.81286212,  0.30729952, -0.82899501,  0.61037027,
         0.89959988,  0.62962884, -0.56018104],
       [-0.31526924,  0.57089051,  3.85273149,  0.95400176,  0.75896922,
         0.51504769,  1.13556564,  0.65139125],
       [-3.24126734,  0.44381943

In [46]:
y

array([-161.59704093,  -52.52921566,  141.64673825, -118.8761106 ,
        214.7662009 ,  -10.13617066,  158.42637621,  384.85830094,
        115.45471128,   74.98142932,  141.46277072,  -46.17257692,
        -56.58742422,   21.50699168,  -69.45673154,  -46.87959085,
         -8.57775891,   75.70207916,  -85.07489561,   15.86426079,
       -145.44817079,  228.53690539,  -39.79813427,  206.06790093,
          8.06053441,  147.32804978,  -90.05198905,   71.47767722,
         46.02736736,  -47.66063379,  -61.5358159 , -155.99238393,
        -58.58884075,  -46.3796142 ,  142.39463485,   66.02400372,
        208.19512548,  156.00412033,   17.12895196,  -48.77752852])

In [47]:
df = pd.DataFrame(x,y)

In [48]:
df

0         1         2         3         4         5  \
-161.597041  0.276691 -0.889514 -0.753736 -0.077102  0.827183 -0.245388   
-52.529216   0.250493 -1.236951  0.781823  0.521942  0.346448  0.259883   
 141.646738  1.579213  0.647689 -0.138264 -0.234153  0.767435  0.496714   
-118.876111 -0.601707 -1.150994  0.110923 -0.600639  1.852278 -0.544383   
 214.766201 -1.519370 -1.260884  0.404982  2.122156 -0.484234  1.765454   
-10.136171  -1.191303  0.293072  0.232254  1.865775  0.656554 -0.680025   
 158.426376  0.747294  0.812862  0.307300 -0.828995  0.610370  0.899600   
 384.858301 -0.315269  0.570891  3.852731  0.954002  0.758969  0.515048   
 115.454711 -3.241267  0.443819 -0.707669 -0.926930 -1.024388  1.266911   
 74.981429  -0.217681  1.277665  0.117327  0.547097  1.098777 -0.020902   
 141.462771  0.515035  1.083051  0.560785 -1.377669  0.513786  0.357787   
-46.172577   0.686260 -0.485364 -0.236819  2.314659 -1.612716 -0.772825   
-56.587424  -1.724918 -0.463418  0.542560  0.241962 -0.562288 -0.469474   
 21.506992  -0.446515  0.473238  0.714000 -0.846794  0.856399 -0.223463   
-69.456732   1.441273  1.632411 -1.247783 -0.440044 -1.435862 -0.252568   
-46.879591  -1.106335  0.331263 -0.309212 -0.479174 -1.196207 -0.839218   
-8.577759   -0.342715  0.005113  0.261055 -1.415371 -0.802277  0.296120   
 75.702079   0.069802 -0.981509  0.010233  0.199060 -0.385314  1.163164   
-85.074896   1.031000  0.324084 -1.763040 -0.676922  0.931280  0.343618   
 15.864261  -0.460639 -0.115648  0.171368 -1.478522  1.057122  0.738467   
-145.448171 -0.919424 -1.550663 -0.503476 -1.062304  1.549934  0.099651   
 228.536905  0.324166  1.305479  0.813510  0.681953 -0.130143  0.825416   
-39.798134   0.091761 -2.619745  1.564644  0.087047 -1.987569 -0.035826   
 206.067901  0.361396 -0.072010  1.356240  0.361636  1.538037  0.812526   
 8.060534   -0.392108  0.097078  0.513267 -0.702053 -1.463515 -0.529760   
 147.328050  1.142823 -0.192361  2.463242 -0.034712  0.751933  0.060230   
-90.051989  -1.607483  0.813517 -0.322062  0.227460  0.184634 -0.783253   
 71.477677  -0.661786  2.143944 -0.651600 -2.025143  0.852433  0.045572   
 46.027367   0.915402  1.477894  0.357113 -0.808494  0.328751 -0.219672   
-47.660634  -0.730367  0.064280  1.088951 -0.715304  0.216459 -0.471932   
-61.535816   0.357015 -0.208122 -0.622700 -0.589365 -0.692910  0.280992   
-155.992384  0.067528 -0.908024  0.314247  1.465649 -1.424748 -1.012831   
-58.588841  -1.328186  0.822545 -1.057711  0.208864  0.196861 -0.013497   
-46.379614  -0.474945  0.504987 -0.114736 -1.200296 -0.653329 -0.792521   
 142.394635 -1.918771  1.886186  0.404051  0.257550 -0.026514 -0.161286   
 66.024004  -0.990536  1.402794 -0.909387  0.586857 -0.566298  0.791032   
 208.195125 -1.070892 -0.264657  1.453534  0.625667  0.482472  0.013002   
 156.004120 -0.151785  1.586017  0.662131  2.133033  0.588317  0.113517   
 17.128952   0.822060  1.158596  0.787085  0.963376  1.896793 -0.974682   
-48.777529   0.058209  0.173181 -1.245739 -0.883857 -1.142970  0.214094   

                    6         7  
-161.597041 -0.815810  0.341152  
-52.529216  -1.320457  0.296985  
 141.646738  1.523030 -0.234137  
-118.876111  0.375698 -0.291694  
 214.766201  0.917862  1.032465  
-10.136171  -0.714351  0.473833  
 158.426376  0.629629 -0.560181  
 384.858301  1.135566  0.651391  
 115.454711  0.774634 -0.059525  
 74.981429  -0.591571 -0.202193  
 141.462771  1.053802 -0.937825  
-46.172577   0.081874 -1.867265  
-56.587424  -0.465730 -1.913280  
 21.506992  -0.072829 -1.514847  
-69.456732  -1.430141  0.130741  
-46.879591   0.975545 -0.185659  
-8.577759   -0.234587 -0.420645  
 75.702079   0.462103 -0.600217  
-85.074896  -0.385082  0.611676  
 15.864261  -0.301104 -0.719844  
-145.448171  0.068563  0.473592  
 228.536905  0.021004 -0.310267  
-39.798134   0.821903 -0.299007  
 206.067901  1.003533 -0.645120  
 8.060534    0.968645 -0.327662  
 147.328050  0.301547 -1.168678  
-90.051989  -1.230864  1.3

In [49]:
xtrain , xtest , ytrain, ytest = tts(x,y,test_size = 0.2,random_state = 42)

In [50]:
xtrain.shape

(32, 8)

In [51]:
xtest.shape

(8, 8)

In [52]:
ytrain.shape

(32,)

In [53]:
ytest.shape

(8,)

In [54]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [55]:
ypred = lr.predict(xtest)

In [56]:
ypred

array([ 15.86426079,  -8.57775891, -46.87959085, -90.05198905,
       214.7662009 , -56.58742422, 156.00412033,  71.47767722])

In [57]:
ytest

array([ 15.86426079,  -8.57775891, -46.87959085, -90.05198905,
       214.7662009 , -56.58742422, 156.00412033,  71.47767722])

In [58]:
lr.score(xtest,ytest)

1.0

In [59]:
from sklearn.linear_model import Ridge,Lasso

In [60]:
lmodel = Lasso()
lmodel.fit(xtrain,ytrain)

Lasso()

In [61]:
lmred = lmodel.predict(xtest)

In [62]:
ytest

array([ 15.86426079,  -8.57775891, -46.87959085, -90.05198905,
       214.7662009 , -56.58742422, 156.00412033,  71.47767722])

In [63]:
lmred

array([ 17.35500077,  -6.13976012, -44.32492356, -87.46507057,
       206.3285404 , -54.49039455, 151.26550097,  72.93294886])

In [64]:
rmodel = Ridge()
rmodel.fit(xtrain,ytrain)

Ridge()

In [65]:
rmpred = rmodel.predict(xtest)

In [66]:
ytest

array([ 15.86426079,  -8.57775891, -46.87959085, -90.05198905,
       214.7662009 , -56.58742422, 156.00412033,  71.47767722])

In [67]:
rmpred

array([ 14.14433454,  -8.06164763, -38.46199987, -82.77752028,
       199.25034665, -52.73771196, 147.44233871,  74.13310746])

In [68]:
print(f'training data score in linear model is {lr.score(xtrain,ytrain)}')
print(f'testing data score in linear model is {lr.score(xtest,ytest)}')

training data score in linear model is 1.0
testing data score in linear model is 1.0


In [69]:
print(f'training data score in Ridge model is {rmodel.score(xtrain,ytrain)}')
print(f'testing data score in Ridge model is {rmodel.score(xtest,ytest)}')

training data score in Ridge model is 0.9981247492949864
testing data score in Ridge model is 0.9942999327265917


In [70]:
print(f'training data score in Lasso model is {lmodel.score(xtrain,ytrain)}')
print(f'testing data score in Lasso model is {lmodel.score(xtest,ytest)}')

training data score in Lasso model is 0.9995570968197268
testing data score in Lasso model is 0.9985033232115915


In [72]:
alpha_lst = [0.01 , 0.02 ,0.03 , 0.04 , 0.05 , 0.06 , 0.07 ,0.08 , 0.19]
for i in alpha_lst:
    r1model = Ridge(alpha = i)
    ridge_model = r1model.fit(xtrain,ytrain)
    r1pred = r1model.predict(xtest)
    print(f' the ridge model score is {r1model.score(xtest,ytest)} while the alpha value is {i} and the error arrya is {r1pred-ypred} ')

 the ridge model score is 0.9999993030818627 while the alpha value is 0.01 and the error arrya is [-0.02235648  0.00381425  0.09505991  0.0805668  -0.17010719  0.03905492
 -0.09513714  0.03230729] 
 the ridge model score is 0.9999972183308994 while the alpha value is 0.02 and the error arrya is [-0.04459173  0.007662    0.1898723   0.16095676 -0.33988224  0.07810288
 -0.19005802  0.06448296] 
 the ridge model score is 0.9999937547058368 while the alpha value is 0.03 and the error arrya is [-0.06670633  0.01154301  0.2844381   0.24117052 -0.50932617  0.11714372
 -0.28476346  0.09652754] 
 the ridge model score is 0.9999889211038681 while the alpha value is 0.04 and the error arrya is [-0.08870089  0.01545706  0.37875828  0.32120871 -0.67843999  0.15617728
 -0.37925429  0.12844156] 
 the ridge model score is 0.9999827263611393 while the alpha value is 0.05 and the error arrya is [-0.11057598  0.01940394  0.47283376  0.40107199 -0.84722472  0.19520339
 -0.47353131  0.16022553] 
 the ridge

In [73]:
alpha_lst = [0.01 , 0.02 ,0.03 , 0.04 , 0.05 , 0.06 , 0.07 ,0.08 , 0.19]
for i in alpha_lst:
    l1model = Lasso(alpha = i)
    lasso_model = l1model.fit(xtrain,ytrain)
    l1pred = l1model.predict(xtest)
    print(f' the lasso model score is {l1model.score(xtest,ytest)} while the alpha value is {i} and the error arrya is {l1pred-ypred} ')

 the lasso model score is 0.9999998552749229 while the alpha value is 0.01 and the error arrya is [ 0.01760533  0.02623423  0.02158051  0.02458498 -0.08325373  0.02111812
 -0.04624754  0.01300549] 
 the lasso model score is 0.9999994099646449 while the alpha value is 0.02 and the error arrya is [ 0.03192998  0.05020373  0.04794385  0.05071444 -0.16779978  0.04205742
 -0.09384509  0.02784135] 
 the lasso model score is 0.9999986648203077 while the alpha value is 0.03 and the error arrya is [ 0.0465798   0.07440335  0.0738589   0.07670119 -0.25226124  0.06301161
 -0.14133006  0.04253129] 
 the lasso model score is 0.9999976196953352 while the alpha value is 0.04 and the error arrya is [ 0.0612957   0.09865132  0.0996871   0.10266125 -0.33671591  0.08397009
 -0.18879631  0.05719561] 
 the lasso model score is 0.9999963096277499 while the alpha value is 0.05 and the error arrya is [ 0.07956043  0.12532922  0.12025341  0.12691456 -0.41962088  0.10513018
 -0.23472904  0.06976007] 
 the lasso