In [2]:
import numpy as np

In [3]:
myar = np.array([3,85,99,32,12,75])

In [4]:
myar

array([ 3, 85, 99, 32, 12, 75])

In [5]:
myar = np.array([[3,85,99,32,12,75]],np.int64)

In [6]:
myar

array([[ 3, 85, 99, 32, 12, 75]], dtype=int64)

In [7]:
myar[0,1]

85

In [8]:
myar.shape

(1, 6)

In [9]:
myar.dtype

dtype('int64')

In [10]:
myar

array([[ 3, 85, 99, 32, 12, 75]], dtype=int64)

In [11]:
myar[0,3] = 485

In [12]:
myar

array([[  3,  85,  99, 485,  12,  75]], dtype=int64)

In [13]:
myar1 = np.array([[1,85,96],
                  [234,-70, 1],
                  [10, 22 ,15]])

In [14]:
myar1

array([[  1,  85,  96],
       [234, -70,   1],
       [ 10,  22,  15]])

In [15]:
myar1.size

9

In [16]:
zeros = np.zeros((3,10))

In [17]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
abc = np.arange(18)

In [19]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [20]:
# Linspace 
# Linear space 

lspace = np.linspace(1,100,15)

In [21]:
lspace

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [22]:
ar5 = np.arange(75)

In [23]:
ar5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [24]:
ar5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [25]:
x = [[15,85,36],[45,89,63],[25,89,77]]

In [26]:
ar = np.array(x)

In [27]:
ar

array([[15, 85, 36],
       [45, 89, 63],
       [25, 89, 77]])

In [28]:
ar6 = np.arange(25)

In [29]:
ar6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
for i in ar6:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [31]:
myar1 = np.array(['apple','orange','cat'])
myar1

array(['apple', 'orange', 'cat'], dtype='<U6')

In [32]:
myar3 = myar1.copy()

In [33]:
myar3

array(['apple', 'orange', 'cat'], dtype='<U6')

In [34]:
myar4 = myar3.view()

In [35]:
myar4

array(['apple', 'orange', 'cat'], dtype='<U6')

In [36]:
myarone = np.ones(10)

In [37]:
myarone

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
myar = np.array([15,25,63,66,14,56,336,98,6,45,75,65])
myar

array([ 15,  25,  63,  66,  14,  56, 336,  98,   6,  45,  75,  65])

In [39]:
#mean
print(np.mean(myar))

72.0


In [40]:
#Median
print(np.median(myar))

59.5


In [41]:
#Min
print(np.min(myar))

6


In [42]:
#Max
print(np.max(myar))

336


In [43]:
#Sum
print(np.sum(myar))

864


In [44]:
#Sort
print(np.sort(myar))

[  6  14  15  25  45  56  63  65  66  75  98 336]


In [45]:
#Reverse Sort
print(np.sort(myar)[::-1])

[336  98  75  66  65  63  56  45  25  15  14   6]


In [46]:
myar

array([ 15,  25,  63,  66,  14,  56, 336,  98,   6,  45,  75,  65])

In [47]:
myar2 = np.array([2,4,6,8])

In [48]:
myar2

array([2, 4, 6, 8])

In [53]:
print(np.power(myar2,2))

[ 4 16 36 64]


In [54]:
myar3 = np.power(myar2,2)
myar3

array([ 4, 16, 36, 64], dtype=int32)

In [55]:
print(np.sqrt(myar3))

[2. 4. 6. 8.]


In [71]:
myar4 = np.array([[1,2,3,4],[5,8,9,7]])
myar5 = np.array([[2,3,4,5],[6,3,4,2]])

In [72]:
print(myar4*myar5)

[[ 2  6 12 20]
 [30 24 36 14]]


In [80]:
# relational operators 
myar10 = np.array([4,25,6,66,31,44])
myar11 = np.array([14,5,10,66,35,44])

In [81]:
print(myar10==myar11)

[False False False  True False  True]


In [76]:
myar13 = myar10+myar11
myar13

array([ 18,  30,  16, 162,  66,  68])

In [78]:
print(np.flip(myar13))

[ 68  66 162  16  30  18]


In [86]:
myar15 = np.array([[25,15,43,63],[85,96,77,63],[85,96,77,63],[85,96,77,63],[85,96,77,63]])
myar15

array([[25, 15, 43, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63]])

In [87]:
print(myar15.transpose())

[[25 85 85 85 85]
 [15 96 96 96 96]
 [43 77 77 77 77]
 [63 63 63 63 63]]


In [93]:
print(myar15[1:3])

[[85 96 77 63]
 [85 96 77 63]]


In [94]:
myar15

array([[25, 15, 43, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63],
       [85, 96, 77, 63]])

In [95]:
print(myar15.flatten())

[25 15 43 63 85 96 77 63 85 96 77 63 85 96 77 63 85 96 77 63]


In [96]:
myar3 = np.array([[[52,45],[58,96],[33,69]]])

In [97]:
myar3

array([[[52, 45],
        [58, 96],
        [33, 69]]])

In [98]:
print(np.ndim(myar3))

3


In [100]:
print(myar3.flatten())

[52 45 58 96 33 69]
